export const SET_USER_CURRENT_LOCATION = "SET_USER_CURRENT_LOCATION";

export const GET_USER_CURRENT_LOCATION = "GET_USER_CURRENT_LOCATION";

export const SET_TRAVELING_POINTS = "SET_TRAVELING_POINTS";