export const SET_USER_CURRENT_LOCATION = "SET_USER_CURRENT_LOCATION";

export const USER_LOADING = "USER_LOADING";

export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_TIPO_DENUNCIA = "GET_TIPO_DENUNCIA";

export const SET_CURRENT_TIPO_DENUNCIA = "SET_CURRENT_TIPO_DENUNCIA";

export const GET_DENUNCIA = "GET_DENUNCIA";

export const SET_CURRENT_DENUNCIA = "SET_CURRENT_DENUNCIA";

export const GET_DENUNCIAS_USUARIO = "GET_DENUNCIAS_USUARIO";

export const ADD_DENUNCIA_USUARIO = "ADD_DENUNCIA_USUARIO";

export const GET_ALL_DENUNCIAS = "GET_ALL_DENUNCIAS";

export const GET_ENDERECO_USUARIO = "GET_ENDERECO_USUARIO";

export const SET_CURRENT_ENDERECO_USUARIO = "SET_CURRENT_ENDERECO_USUARIO";

export const ADD_ENDERECO_USUARIO = "ADD_ENDERECO_USUARIO";

export const LOADING = "LOADING";

export const LOADED = "LOADED";

export const SET_SEARCHED_PLACE = "SET_SEARCHED_PLACE";

export const SET_ORIGIN = "SET_ORIGIN";

export const SET_DESTINATION = "SET_DESTINATION";

export const CANCEL_MAP_OPERATIONS = "CANCEL_MAP_OPERATIONS";

export const SET_DIRECTIONS = "SET_DIRECTIONS";

export const SET_TRAVELLING_MODE = "SET_TRAVELLING_MODE";

export const SET_PLACE_KIND = "SET_PLACE_KIND";
